---
# RedHat tasks file for ansible-role-grub-security

- name: "Ensure SELinux is not disabled in bootloader config"
  ansible.builtin.shell: grubby --update-kernel ALL --remove-args 'selinux=0 enforcing=0'

- name: "Set the appropriate permissions on the Grub config file"
  ansible.builtin.file:
    path: "{{ grubcfg }}"
    owner: root
    group: root
    mode: '0600'

- name: "Set the appropriate permissions on the Grub environment file"
  ansible.builtin.file:
    path: "{{ grubenv }}"
    owner: root
    group: root
    mode: '0600'

- name: "Set the appropriate permissions on the Grub User config file"
  ansible.builtin.file:
    path: "{{ userfile }}"
    owner: root
    group: root
    mode: '0600'
