---
# RedHat tasks file for ansible-role-grub-security

- name: "Ensure SELinux is not disabled in bootloader config"
  ansible.builtin.shell: grubby --update-kernel ALL --remove-args 'selinux=0 enforcing=0'
